#!/bin/bash

test ${BASH_VERSION:0:1} -eq 4 || { echo "I require bash 4.0.0+! ._."; exit 1; }

cd markizano/;
echo "[*] Generating MD5 checksums.";
find ./ -regextype posix-egrep ! -regex '.*/?DEBIAN/.*' -type f -printf "%P\n" | sort | xargs md5sum > DEBIAN/md5sums
cd ..;

dpkg-deb --build markizano;
