#!/bin/sh
# [Gedit Tool]
# Comment=Run "make" in the document directory
# Name=Build
# Shortcut=<Control>F8
# Languages=
# Applicability=local
# Input=nothing
# Output=output-panel
# Save-files=document


EHOME=`echo $HOME | sed "s/#/\#/"`
DIR=$GEDIT_CURRENT_DOCUMENT_DIR
while test "$DIR" != "/"; do
    for m in GNUmakefile makefile Makefile; do
        if [ -f "${DIR}/${m}" ]; then
            echo "Using ${m} from ${DIR}" |
            	sed "s#$EHOME#~#"
            make -C "${DIR}"
            exit
        fi
    done
    DIR=`dirname "${DIR}"`
done
echo "No Makefile found!" > /dev/stderr
