#!/bin/bash
# [Gedit Tool]
# Name=gMaps
# Shortcut=<Control><Alt>m
# Applicability=all
# Output=replace-selection
# Input=selection
# Save-files=document


export DISPLAY=:0.0;
ID=$(cat /dev/stdin);
xclip -selection c -o | php -r '$link = fGets(STDIN); $url = parse_url($link); parse_str($url["query"], $query); list($lat, $lng) = explode(",", isset($query["ll"])? $query["ll"]: $query["sll"]); echo "UPDATE `apts` SET `lat` = '\'\$lat\'', `lng` = '\'\$lng\'' WHERE `id` = '\''{$_SERVER["argv"][1]}'\'\;\\n\"\; "$ID";
