#!/bin/bash
# [Gedit Tool]
# Name=mxml
# Shortcut=<Control>m
# Applicability=all
# Output=output-panel
# Input=document
# Save-files=document


debug=mxmlc
[ -x "$PWD/debug" ] && debug="$PWD/debug";

$debug $GEDIT_CURRENT_DOCUMENT_PATH;
