#!/bin/bash
# [Gedit Tool]
# Name=PHP
# Shortcut=<Control>F5
# Applicability=all
# Output=output-panel
# Input=document
# Save-files=document


/bin/php -c /etc/php5/php.ini $GEDIT_CURRENT_DOCUMENT_PATH;
