#!/bin/bash
# [Gedit Tool]
# Name=WordWrap
# Shortcut=<Control>F6
# Applicability=all
# Output=replace-selection
# Input=selection
# Save-files=document


export WORDWRAP=85
/usr/bin/fold -sw$WORDWRAP | sed -r 's/\s*$//'
